# https://github.com/AllTheMods/alltheservers
#
# The MIT License (MIT)
#
# Copyright (c) 2018 BloodWorkXGaming
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.


# Version of the specs, only for internal usage if this format should ever change drastically
_specver: 2

# modpack related settings, changes the supposed to change the visual appearance of the launcher
modpack:
  # Name of the mod pack, that is displayed in various places where it fits
  name: CraftBlock

  # Description
  description: CraftBlock stands for Craft Attack 3 Skyblock and is an expert skyblock modpack like FTB Infinity Evolved Skyblock.


# settings regarding the installation of the modpack
install:
  # version of minecraft, needs the exact version
  mcVersion: 1.12.2

  # exact version of forge or fabric that is supposed to be used
  # if this value is a null value so ( ~, null, or "" ) then the version from the mod pack is going to be used
  loaderVersion: ~

  # If a custom installer is supposed to used, specify the url here: (Otherwise put "", ~ or null here)
  # supports variables: {{@loaderversion@}} and {{@mcversion@}}
  # For forge: "http://files.minecraftforge.net/maven/net/minecraftforge/forge/{{@mcversion@}}-{{@loaderversion@}}/forge-{{@mcversion@}}-{{@loaderversion@}}-installer.jar"
  # For Fabric: "https://maven.fabricmc.net/net/fabricmc/fabric-installer/{{@loaderversion@}}/fabric-installer-{{@loaderversion@}}.jar"
  installerUrl: http://files.minecraftforge.net/maven/net/minecraftforge/forge/{{@mcversion@}}-{{@loaderversion@}}/forge-{{@mcversion@}}-{{@loaderversion@}}-installer.jar

  # Installer Arguments
  # These Arguments have to be passed to the installer
  #
  # For Fabric:
  # installerArguments:
  #    - "server"
  #    - "-downloadMinecraft"
  #    - "-snapshot"
  #    - "-mcversion"
  #    - "1.16.4"
  #    - "-loader"
  #    - "0.10.6+build.214"
  #
  # For Forge:
  # installerArguments:
  #   - "--installServer"
  installerArguments:
    - "--installServer"

  # Link to where the file where the modpack can be distributed
  # This supports loading from local files as well for most pack types if there is file://{PathToFile} in the beginning
  modpackUrl: https://media.forgecdn.net/files/3449/926/CraftBlock-1.1.1.zip

  # This is used to specify in which format the modpack is distributed, the server launcher has to handle each individually if their format differs
  # current supported formats:
  # - curseforge or curse
  # - curseid
  # - zip or zipfile
  modpackFormat: curse

  # Settings which are specific to the format used, might not be needed in some casese
  formatSpecific:
    # optional paramenter used for curse to specify a whole project to ignore (mostly if it is client side only)
    ignoreProject:
      - 243478 # More Overlays
      - 250398 # Controlling
      - 268324 # Blur
      - 333760 # Splash Logo Color Fix
      - 237701 # ReAuth
      - 231275 # Ding
      # - 226447 # Resource Loader
      - 60089 # Mouse Tweaks

  # The base path where the server should be installed to, ~ for current path
  baseInstallPath: ~

  # a list of files which are supposed to be ignored when installing it from the client files
  # this can either use regex or glob {default glob: https://docs.oracle.com/javase/8/docs/api/java/nio/file/FileSystem.html#getPathMatcher-java.lang.String-}
  # specify with regex:.... or glob:.... if you want to force a matching type
  ignoreFiles:
    - resources/**

  # often a server needs more files, which are nearly useless on the client, such as tickprofiler
  # This is a list of files, each ' - ' is a new file:
  # url is the directlink to the file, destination is the path to where the file should be copied to
  # additionalFiles:
  #   - url: https://media.forgecdn.net/files/3101/200/tellme-fabric-1.16.4-0.9.1-beta.1.jar
  #     destination: mods/tellme-fabric-1.16.4-0.9.1-beta.1.jar
  #   - url: https://media.forgecdn.net/files/3097/870/blocklogger-0.2.1.jar
  #     destination: mods/blocklogger-0.2.1.jar
#    - url: https://media.forgecdn.net/files/3072/467/BlueMap-1.2.0-snap-fabric-1.16.3.jar
#      destination: mods/BlueMap-1.2.0-snap-fabric-1.16.3.jar
  #   - url: https://media.forgecdn.net/files/3082/894/hypnos-0.1.1.jar
  #     destination: mods/hypnos-0.1.1.jar
  #   - url: https://media.forgecdn.net/files/3109/728/InvView-1.2.0-1.16.2%2B.jar
  #     destination: mods/InvView-1.2.0-1.16.2%2B.jar
  #   - url: https://media.forgecdn.net/files/3098/760/FabriKommander-1.0.0-MC1.16.3.jar
  #     destination: mods/FabriKommander-1.0.0-MC1.16.3.jar
#    - url: https://media.forgecdn.net/files/3104/633/flan-1.16.2-1.1.4.jar
#      destination: mods/flan-1.16.2-1.1.4.jar
  #   - url: https://ci.lucko.me/job/spark/lastSuccessfulBuild/artifact/spark-fabric/build/libs/spark-fabric.jar
  #     destination: mods/spark-fabric.jar
  #   - url: https://media.forgecdn.net/files/3115/560/disfabric-1.16.4-1.2.0.jar
  #     destination: mods/disfabric-1.16.4-1.2.0.jar
  #   - url: https://media.forgecdn.net/files/3009/753/shutupconsole-1.1.jar
  #     destination: mods/shutupconsole-1.1.jar
  #   - url: https://cdn.discordapp.com/attachments/750220836191076383/778900805402492958/advdebug-2.2.0.jar
  #     destination: mods/advdebug-2.2.0.jar

  # For often there are config which the user wants to change, here is the place to put the local path to configs, jars or whatever
  # You can copy files or folders:
  #
  # localFiles:
  #   - from: OLD_TO_DELETE/config/disfabric.json5
  #     to: config/disfabric.json5
  #   - from: OLD_TO_DELETE/config/charm.toml
  #     to: config/charm.toml
  #   - from: OLD_TO_DELETE/config/hypnos.json
  #     to: config/hypnos.json
  #   - from: OLD_TO_DELETE/config/shutupconsole.toml
  #     to: config/shutupconsole.toml
  #   - from: OLD_TO_DELETE/kubejs/server_scripts/custom.js
  #     to: kubejs/server_scripts/custom.js
  #   - from: OLD_TO_DELETE/config/indrev/cables.json
  #     to: config/indrev/cables.json

  # This makes the program check the folder for whether it is supposed to use the
  checkFolder: yes

  # Whether to install the Loader (Forge or Fabric) or not, should always be yes/true unless you only want to install the pack
  installLoader: yes

  # Sponge bootstrapper jar URL
  # Only needed if you have spongefix enabled
  spongeBootstrapper: https://github.com/simon816/SpongeBootstrap/releases/download/v0.7.1/SpongeBootstrap-0.7.1.jar




# settings regarding the launching of the pack
launch:
  # applies the launch wrapper to fix sponge for a few mods
  spongefix: no

  # Use a RAMDisk for the world folder
  # case-sensitive; use only lowercase `yes` or `no`
  # NOTE: The server must have run once fully before switching to `yes`!
  ramDisk: no

  # checks with the help of a few unrelated server whether the server is online
  checkOffline: no

  # specifies the max amount of ram the server is supposed to launch with
  maxRam: 4G

   # specifies the minimal amount of ram the server is supposed to launch with
  # minRam: 4G

  # specifies whether the server is supposed to auto restart after crash
  autoRestart: yes

  # after a given amount of crashes in a given time the server will stop auto restarting
  crashLimit: 10

  # Time a crash should be still accounted for in the {crashLimit}
  # syntax is either [number]h or [number]min or [number]s
  crashTimer: 60min

  # Arguments that need to go before the 'java' argument, something like linux niceness
  # This is only a string, not a list.
  preJavaArgs: ~

  # Start File Name, variables: {{@loaderversion@}} and {{@mcversion@}}
  # This has to be the name the installer spits out
  # For Forge 1.12-: "forge-{{@mcversion@}}-{{@loaderversion@}}-universal.jar"
  # For Forge 1.13+: "forge-{{@mcversion@}}-{{@loaderversion@}}.jar"
  # For Fabric: "fabric-server-launch.jar"
  startFile: forge-{{@mcversion@}}-{{@loaderversion@}}-universal.jar

  # In case you have multiple javas installed you can add a absolute path to it here
  # if the value is "", null, or ~ then 'java' from PATH is going to be used
  # Example: "\"C:/Program Files/Java/jre1.8.0_201/bin/java.exe\""
  forcedJavaPath: ~

  # Java args that are supposed to be used when the server launches
  # keep in mind java args often need ' - ' in front of it to work, use clarifying parentheses to make sure it uses it correctly
  # Keep in mind that some arguments only work on JRE 1.8
  javaArgs:
    - "-XX:+UseG1GC"
    - "-XX:+ParallelRefProcEnabled"
    - "-XX:MaxGCPauseMillis=30"
    - "-XX:+UnlockExperimentalVMOptions"
    - "-XX:+DisableExplicitGC"
    - "-XX:+AlwaysPreTouch"
    - "-XX:G1NewSizePercent=30"
    - "-XX:G1MaxNewSizePercent=40"
    - "-XX:G1HeapRegionSize=8M"
    - "-XX:G1ReservePercent=25"
    - "-XX:G1HeapWastePercent=5"
    - "-XX:G1MixedGCCountTarget=4"
    - "-XX:InitiatingHeapOccupancyPercent=15"
    - "-XX:G1MixedGCLiveThresholdPercent=90"
    - "-XX:G1RSetUpdatingPauseTimePercent=5"
    - "-XX:SurvivorRatio=32"
    - "-XX:+PerfDisableSharedMem"
    - "-XX:MaxTenuringThreshold=1"
    - "-Dusing.aikars.flags=https://mcflags.emc.gs"
    - "-Daikars.new.flags=true"
    - "-XX:ConcGCThreads=3"
    - "-XX:ParallelGCThreads=12"