# This is a basic workflow to help you get started with Actions

name: CI Server Pack

# Controls when the workflow will run
on:
  # Triggers the workflow on release
  release:
    types: [published]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          cp -r template/ server/world/
          cp LICENSE server/LICENSE
          sed -i 's#modpackplaceholderurl#https://github.com/sebinside/CraftBlock/releases/download/v1.2.0/CraftBlock-1.2.0.zip#g' server/server-setup-config.yaml
          zip -r CraftBlock-Server-1.2.0.zip server/
